In [2]:
#1 какие еще существуют коды типов?
#2 напишите код, подобный приведенному выше, но с другим типом

In [3]:
#'b'-signed char, int

#'B'-unsigned charint

#'u'-wchar_t, Unicode character

#'w'-Py_UCS4, Unicode character

#'h'-signed short, int

#'H'-unsigned short, int

#'i'-signed int, int

#'I'-unsigned int, int

#'l'-signed long, int

#'L'-unsigned long, int

#'q'-signed long long, int

#'Q'-unsigned long long, int

#'f'-float, float

#'d'-double, float

In [4]:
import array
import sys

a1 = array.array('l')
a2 = array.array('I', [1, 2, 3, 4, 5])
a3 = array.array('l', [1, 2, 3, 4, 5])
a4 = array.array('d', [1.0, 2.0, 3.14])

print (sys.getsizeof(a1))
print (sys.getsizeof(a2))
print (sys.getsizeof(a3))
print (sys.getsizeof(a4))

80
100
100
104


In [5]:
##3. напишите код для создания массива с 5 значениями, распологающимися через равные интервалы
##в диапазоне от 0 до 1 

In [6]:
import numpy as np
print (np.arange(0, 1, 0.2))

[0.  0.2 0.4 0.6 0.8]


In [7]:
##4. напишите код для создания массива с 5 равномерно распределенными случайными значениями
##в диапазоне от 0 до 1

In [8]:
x1 = np.random.uniform(0, 1, 5)
print(x1)

[0.95056525 0.37554111 0.07933989 0.62196741 0.03044045]


In [9]:
##5. напишите код для создания массива с 5 нормально распределенными случайными значениями
##с мат. ожиданием =0 и дисперсией 1

In [10]:
x2=np.random.normal(0, 1, (5))
print(x2)

[ 0.63082816  2.70307345 -2.44690189 -0.44101217  0.69444907]


In [11]:
##6. Напишите код для создания массива с 5 случайными целыми числами от [0,10)

In [12]:
np.random.seed(1) #установка начального значения, уникальная подборка рандомных чисел
x3 = np.random.randint(10, size=5)
print(x3)

[5 8 9 5 0]


In [13]:
##7. Написать код для создания срезов массива 3 на 4 
#- первые две строки и три столбца
#-первые три строки и второй столбец
#- все строки и столбцы в обратном порядке
#-второй столбец
#-третья строка

In [14]:
x6=np.random.randint(10, size=(3,4))
print(x6)

[[0 1 7 6]
 [9 2 4 5]
 [2 4 2 4]]


In [15]:
print(x6[1][3])

5


In [16]:
print(x6[0:2,0:3])

[[0 1 7]
 [9 2 4]]


In [17]:
print(x6[0:3,1])

[1 2 4]


In [18]:
print(x6[::-1,::-1])

[[4 2 4 2]
 [5 4 2 9]
 [6 7 1 0]]


In [19]:
print(x6[0:,1])

[1 2 4]


In [20]:
print(x6[2,0:])

[2 4 2 4]


In [21]:
## 8. Продемонстрируйте как сделать срез-копию 

In [22]:
x6_copy=x6[:]
print(x6_copy)

[[0 1 7 6]
 [9 2 4 5]
 [2 4 2 4]]


In [23]:
## 9.  продемонстрируйте использование newaxis для получения эффекта вектора-стобца и вектора-строки из массива

In [24]:
x9=np.array([0,1,2,3,4])
x9[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [25]:
x9[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [26]:
x91=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(x91)
x91[:, np.newaxis]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [27]:
x91[np.newaxis,:]

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [56]:
##10. Разобратся как работает метод dstack 
# Укладывайте массивы последовательно по глубине (вдоль третьей оси).

In [58]:
x10 = np.array((1,2,3))
y10 = np.array((2,3,4))
np.dstack((x10, y10))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [60]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [ ]:
##11. Разобратся как работает методы split, vsplit, dsplit

In [ ]:
#numpy.split(ary, indices_or_sections, axis=0)
#Разделите массив на несколько подмассивов в виде представлений в ary.

In [64]:
import numpy as np
x11 = np.arange(9.0)
print(x11)
np.split(x11, 3)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [68]:
x11 = np.arange(8.0)
print(x11)
np.split(x11, [3, 5])

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]), array([3., 4.]), array([5., 6., 7.])]

In [72]:
x11 = np.arange(8.0)
print(x11)
np.split(x11, [2, 5,6])

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1.]), array([2., 3., 4.]), array([5.]), array([6., 7.])]

In [ ]:
#numpy.vsplit(ary, indices_or_sections)
#Разделите массив на несколько подмассивов по вертикали (по строкам).

In [78]:
x = np.arange(16.0).reshape(4, 4)
print(x)
np.vsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [94]:
x1 = np.arange(16.0).reshape(2, 8)
print(x1)
np.vsplit(x1, np.array([2, 2]))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]


[array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]]),
 array([], shape=(0, 8), dtype=float64),
 array([], shape=(0, 8), dtype=float64)]

In [86]:
x = np.arange(16.0).reshape(4, 4)
np.vsplit(x, np.array([2, 2]))

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([], shape=(0, 4), dtype=float64),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [96]:
x = np.arange(8.0).reshape(2, 2, 2)
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]),
 array([[[4., 5.],
         [6., 7.]]])]

In [ ]:
#numpy.dsplit(ary, indices_or_sections)
#Split array into multiple sub-arrays along the 3rd axis (depth).
#dsplit only works on arrays of 3 or more dimensions

In [100]:
x = np.arange(8.0).reshape(2, 2, 2)
print(x)
np.dsplit(x,2)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


[array([[[0.],
         [2.]],
 
        [[4.],
         [6.]]]),
 array([[[1.],
         [3.]],
 
        [[5.],
         [7.]]])]

In [ ]:
##12. Привести пример использования всех универсальных функций - - / // ** % np.abs, sin/cos/tan... , exp, log

In [102]:
x6=np.arange(10)
print (x6)
print(x6//2)

[0 1 2 3 4 5 6 7 8 9]
[0 0 1 1 2 2 3 3 4 4]


In [106]:
print(x6/2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [108]:
print(x6**2)

[ 0  1  4  9 16 25 36 49 64 81]


In [110]:
print(x6%4)

[0 1 2 3 0 1 2 3 0 1]


In [114]:
x=np.arange(-2, 0, 0.5)
print(x)

[-2.  -1.5 -1.  -0.5]


In [116]:
x=np.abs(x)
print(x)

[2.  1.5 1.  0.5]


In [120]:
x=np.arange(0,1,0.2)
x=np.sin(x)
print(x)

[0.         0.19866933 0.38941834 0.56464247 0.71735609]


In [122]:
x=np.arange(0,1,0.2)
x=np.tan(x)
print(x)

[0.         0.20271004 0.42279322 0.68413681 1.02963856]


In [124]:
x=np.arange(0,1,0.2)
x=np.exp(x)
print(x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093]


In [130]:
x=np.arange(0.2,1,0.1)
x=np.log(x)
print(x)

[-1.60943791 -1.2039728  -0.91629073 -0.69314718 -0.51082562 -0.35667494
 -0.22314355 -0.10536052]
