In [3]:
import numpy as np

In [ ]:
## 1. Что надо изменить в последнем примере, чтобы он заработал без ошибок (транслирование)?


In [ ]:
# Исходный пример:

In [5]:
a = np.ones((3,2))
b = np.arange(3)

# 2 (3,2)    (3,2)    (3,2)
# 1 (3,)  -> (1,3) -> (3,3)

c=a+b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
# Правила
# 1. Если размерности массивов отличаются, то форма массива с меньшей размерностью дополняется 1 с левой стороны
# 2. Если формы массивов не совпавдают в каком-то измерении, то если у массива форма=1, то он "расстягивается"
# до соответств формы второго массива
# 3. Если после применения этих правил в каком-дибо измерении размеры отличаются и ни один из них не равен 1,
# то генерируется ошибка

In [ ]:
# Исправленная версия:

In [11]:
a = np.ones((3,2))
b = np.arange(2)

c=a+b

# 2 (3,2)    (3,2)    (3,2)
# 1 (2,)  -> (1,2) -> (3,2)

print(a)
print(b)
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1]
[[1. 2.]
 [1. 2.]
 [1. 2.]]


In [ ]:
## 2. Пример для y. Вычислить количество элементов (по обоим размерностям), значения которых больше 3 и меньше 9

In [13]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
print(np.sum(y > 3, axis=0)) # больше 3 по  столбцам

[1 1 1 2 2]


In [17]:
print(np.sum(y > 3, axis=1)) # больше 3 по  строкам

[2 5]


In [21]:
print(np.sum(y < 9, axis=0)) # меньше 9 по  столбцам

[2 2 2 1 1]


In [23]:
print(np.sum(y < 9, axis=1)) # меньше 9 по  строкам

[5 3]
