In [3]:
import numpy as np
import pandas as pd


In [3]:
# 1. Привести различные способы создания объектов типа Series
#-списки Python или массивы NumPy
#-скалярные значение
#-словари


In [5]:
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [11]:
ndarr = np.array([1, 2, 3, 4, 5])
type(ndarr)


numpy.ndarray

In [13]:
s2 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int32


In [15]:
d = {'a':1, 'b':2, 'c':3}
s3 = pd.Series(d)
print(s3)

a    1
b    2
c    3
dtype: int64


In [17]:
a = 7
s4 = pd.Series(a, ['a', 'b', 'c'])
print(s4)

a    7
b    7
c    7
dtype: int64


In [19]:
# 2. Привести различные способы создания DataFrame.
#- через объекты Series
# - списки словарей
# - словари объектов Series
# - двумерный массив NumPy
# - структурированный массив NumPy

In [23]:
d = {"price":pd.Series([1, 2, 3], index=['v1', 'v2', 'v3']),
 "count": pd.Series([10, 12, 7], index=['v1', 'v2', 'v3'])}
df1 = pd.DataFrame(d)
print(df1)

    price  count
v1      1     10
v2      2     12
v3      3      7


In [25]:
d2 = {"price":np.array([1, 2, 3]), "count": np.array([10, 12, 7])}
df2 = pd.DataFrame(d2, index=['v1', 'v2', 'v3'])
print(df2)

    price  count
v1      1     10
v2      2     12
v3      3      7


In [27]:
d3 = [{"price": 3, "count":8}, {"price": 4, "count": 11}]
df3 = pd.DataFrame(d3)
print(df3)

   price  count
0      3      8
1      4     11


In [29]:
nda1 = np.array([[1, 2, 3], [10, 20, 30]])
df4 = pd.DataFrame(nda1)
print(df4)

    0   1   2
0   1   2   3
1  10  20  30


In [31]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы
# вместо NaN было установлено значение 1

In [49]:
rng = np.random.default_rng()
dfA = pd.DataFrame(rng.integers(0,10,(2,2)), columns =['a','b'])
dfB = pd.DataFrame(rng.integers(0,10,(3,3)), columns =['a','b', 'c'])

print(dfA)
print(dfB)

print ((dfA + dfB).fillna(1))

   a  b
0  3  0
1  6  0
   a  b  c
0  8  1  9
1  3  1  2
2  1  3  0
      a    b    c
0  11.0  1.0  1.0
1   9.0  1.0  1.0
2   1.0  1.0  1.0


In [55]:
rng = np.random.default_rng()
dfA2 = pd.DataFrame(rng.integers(0,10,(2,2)), columns =['a','b'])
dfB2 = pd.DataFrame(rng.integers(0,10,(3,3)), columns =['a','b', 'c'])

print (dfA2)
print (dfB2)

print (dfA2.add(dfB2, fill_value=1))

   a  b
0  7  3
1  4  7
   a  b  c
0  7  9  8
1  3  9  6
2  7  7  1
      a     b    c
0  14.0  12.0  9.0
1   7.0  16.0  7.0
2   8.0   8.0  2.0


In [34]:
# 4. Переписать пример с транслированием для DataFrame так, чтобы вычитание происходило 
# по столбцам, а не по строкам

In [69]:
rng = np.random.default_rng(1)

A = rng.integers(0, 10, (3,4))
print(A)

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]


In [71]:
df = pd.DataFrame(A, columns=['a','b','c','d'])
print(df)

   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4


In [73]:
print (df.iloc[0, ::2])

a    4
c    7
Name: 0, dtype: int64


In [77]:
# Транспонируем -> вычитаем -> транспонируем обратно
result = (df.T - df.iloc[0, ::2]).T

print(result)

    a   b   c   d
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
a NaN NaN NaN NaN
c NaN NaN NaN NaN


In [37]:
#5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()
# ffill() (прямое заполнение) заполняет пропущенные значения предыдущим допустимым значением в столбце.

# bfill() (обратное заполнение) заполняет пропущенные значения следующим допустимым значением в столбце.


In [63]:
df = pd.DataFrame(
    {
        "Max Temperature": [22.7, 24.8, np.nan, np.nan, 29.9, np.nan, 45],
        "Min Temperature": [np.nan, 20.1, 18.4, np.nan, np.nan, np.nan, 15.5],
        "Avg Temperature": [21.4, 23.5, np.nan, 20.3, np.nan, 19.8, 20.4]
    }
)
print(df)

ffill_df = df.ffill()
print(ffill_df)

   Max Temperature  Min Temperature  Avg Temperature
0             22.7              NaN             21.4
1             24.8             20.1             23.5
2              NaN             18.4              NaN
3              NaN              NaN             20.3
4             29.9              NaN              NaN
5              NaN              NaN             19.8
6             45.0             15.5             20.4
   Max Temperature  Min Temperature  Avg Temperature
0             22.7              NaN             21.4
1             24.8             20.1             23.5
2             24.8             18.4             23.5
3             24.8             18.4             20.3
4             29.9             18.4             20.3
5             29.9             18.4             19.8
6             45.0             15.5             20.4


In [65]:
bfill_df = df.bfill()
print(bfill_df)

   Max Temperature  Min Temperature  Avg Temperature
0             22.7             20.1             21.4
1             24.8             20.1             23.5
2             29.9             18.4             20.3
3             29.9             15.5             20.3
4             29.9             15.5             19.8
5             45.0             15.5             19.8
6             45.0             15.5             20.4
