In [1]:
import array
import sys
import numpy as np

#Типы данных питона
x = 1
print (type(x))

<class 'int'>


In [2]:
import sys
print (sys.getsizeof(x))


28


In [3]:
l2=list([1,2,3])
print (sys.getsizeof(l2))

88


In [4]:
l3=list([1, "2", True])
print(l3)

[1, '2', True]


In [5]:
a1 = array.array('i',[1,2,3])
print (sys.getsizeof(a1))

92


In [6]:
# какие еще существуют коды типов?
# напишите код, подобный приведенному выше, но с другим типом

In [7]:
a=np.array([1,2,3,4,5])
print (type(a),a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [8]:
a=np.array([1.23,2,3,4,5], dtype=int)
print (type(a),a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [9]:
a=np.array([range(i, i+3) for i in [2,4,6]])
print(a, type(a))

[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>


In [10]:
b1=np.zeros(10, dtype=int)
print (b1, type(b1))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [11]:
print (np.ones((3,5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
print (np.full((4,5), 3.1415))

[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]


In [13]:
print (np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
print (np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
##3. напишите код для создания массива с 5 значениями, распологающимися через равные интервалы
##в диапазоне от 0 до 1 
##4. напишите код для создания массива с 5 равномерно распределенными случайными значениями
##в диапазоне от 0 до 1
##5. напишите код для создания массива с 5 нормально распределенными случайными значениями
##с мат. ожиданием =0 и дисперсией 1
##6. Напишите код для создания массива с 5 случайными целыми числами от [0,10)

In [16]:
###МАССИВЫ

In [17]:
np.random.seed(1) #установка начального значения, уникальная подборка рандомных чисел
x1 = np.random.randint(10, size=3)
print(x1)

[5 8 9]


In [18]:
x2=np.random.randint(10, size=(3,2))
print(x2)

[[5 0]
 [0 1]
 [7 6]]


In [19]:
x3=np.random.randint(10, size=(3,2,1))
print(x3)

[[[9]
  [2]]

 [[4]
  [5]]

 [[2]
  [4]]]


In [20]:
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 1) 6


In [21]:
ar = np.array([1,2,3,4,5])
print(ar[0])

1


In [22]:
print(ar[-2])

4


In [23]:
ar[1]=20
print(ar)

[ 1 20  3  4  5]


In [24]:
ar1 = np.array([[1,2], [3,4]])
print(ar1)

print(ar1[0,0])
print(ar1[-1,-1])

ar1[1,0]=100
print(ar1)

[[1 2]
 [3 4]]
1
4
[[  1   2]
 [100   4]]


In [25]:
a3 = np.array([1,2,3,4])
b3=np.array([1.0,2,3,4])

print(a3)
print(b3)

[1 2 3 4]
[1. 2. 3. 4.]


In [26]:
a3[0]=10
print(a3)

[10  2  3  4]


In [27]:
a3[0]=10.123 ##тип данных не будет меняться из-за изначально созданного массива с типом данных int
print(a3)

[10  2  3  4]


In [28]:
##СРЕЗ (ПОДМАССИВ) [start:finish:step] [0:shape:1]

In [29]:
a4 = np.array([1,2,3,4,5,6])
print(a4[0:3:1])

[1 2 3]


In [30]:
print(a4[:3])##index<2

[1 2 3]


In [31]:
print(a4[3:]) ##index>2

[4 5 6]


In [32]:
print(a4[1:-1])
print(a4[1::2]) 

[2 3 4 5]
[2 4 6]


In [33]:
print(a4[::-1])

[6 5 4 3 2 1]


In [34]:
d = a4[:3]
print(d)
d[0]=100
print(a4)

[1 2 3]
[100   2   3   4   5   6]


In [35]:
##7. Написать код для создания срезов массива 3 на 4 
#- первые две строки и три столбца
#-первые три строки и второй столбец
#- все строки и столбцы в обратном порядке
#-второй столбец
#-третья строка

## 8. Продемонстрируйте как сделать срез-копию 

In [36]:
a5=np.arange(1,13)
print(a5)
print(a5.reshape(2,6))
print(a5.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
## 9. newaxis продемонстрируйте использование для получения эффекта вектора-стобца и вектора-строки из массива


In [38]:
x = np.array([1,2,3])
y = np.array([4,5])
z = np.array([6])

print(np.concatenate([x,y,z]))

[1 2 3 4 5 6]


In [39]:
x2 = np.array([1,2,3])
y2 = np.array([4,5,6])

r2 = np.vstack([x2,y2])
print(r2)

[[1 2 3]
 [4 5 6]]


In [40]:
print(np.hstack([r2,r2]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [41]:
##10. Разобратся как работает метод dstack 
##11. Разобратся как работает методы split, vsplit, dsplit

In [42]:
##ВЫЧИСЛЕНИЯ С МАССИВАМИ

In [43]:
#ВЕКТОРИЗИРОВАННАЯ ОПЕРАЦИЯ- независимо к каждому элементу

In [44]:
x6=np.arange(10)
print (x6)

print(x6*2 + 1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [45]:
#Универсальные функции

In [46]:
print (np.add(np.multiply(x6,2),1))

[ 1  3  5  7  9 11 13 15 17 19]


In [47]:
# - - / // ** %

In [48]:
##12. Привести пример использования всех универсальных функций, которые я привел
## np.abs, sin/cos/tan... , exp, log, 

In [49]:
x7 = np.arange(5)
print(np.multiply(x7,10))
print(x7)

[ 0 10 20 30 40]
[0 1 2 3 4]


In [50]:
x8 = np.arange(5)
y8= np.empty(5)
print(np.multiply(x7,10, out =y8))
print(y8)

[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]


In [51]:
x8 = np.arange(5)
y8= np.zeros(10)
print(np.multiply(x7,10, out =y8[::2]))
print(y8)

[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [52]:
x9 = np.arange(1,5)
print(x9)
print(np.add.reduce(x9))
print(np.add.accumulate(x9))

[1 2 3 4]
10
[ 1  3  6 10]


In [53]:
## векторные произведение

In [54]:
x10=np.arange(1,10)
print(np.add.outer(x10,x10))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]


In [55]:
print(np.multiply.outer(x10,x10))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
