In [1]:
import numpy as np
import pandas as pd


In [3]:
#Pandas - расширение NumPy (структурированные массивы). Строки и столбцы индексируются метками,
# а не только числовыми значениями
#Series, DataFrame, Index
#

In [5]:
## Seried

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print (data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [11]:
print(type(data))

<class 'pandas.core.series.Series'>


In [15]:
print(data.values)
print(type(data.values))

print(data.index)
print(type(data.index))

[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>


In [17]:
print (data[0])

0.25


In [19]:
print(data[1:3])

1    0.50
2    0.75
dtype: float64


In [21]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c', 'd'])
print(data)
print(data['a'])
print(data['b':'d'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [23]:
print(type(data.index))

<class 'pandas.core.indexes.base.Index'>


In [25]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1,10,7, 'd'])

In [27]:
print(data[1])
print(data[10:'d'])

0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [29]:
population_dict = {
    'city_1' : 1001,
    'city_2' : 1002,
    'city_3' : 1003,
    'city_4' : 1004,
    'city_5' : 1005,
}
population = pd.Series(population_dict)
print(population)

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64


In [37]:
print (population['city_4'])
print (population['city_4':'city_5'])      

1004
city_4    1004
city_5    1005
dtype: int64


In [ ]:
## Для создания Series можно использовать
#-списки Python или массивы NumPy
#-скалярные значение
#-словари
# 1. Привести различные способы создания объектов типа Series

In [ ]:
## DataFrame - двумерный массив с явно определенными индексами. Последовательность 
# "согласованных" объектов Series

In [41]:
population_dict = {
    'city_1' : 1001,
    'city_2' : 1002,
    'city_3' : 1003,
    'city_4' : 1004,
    'city_5' : 1005,
}
area_dict = {
    'city_1' : 9991,
    'city_2' : 9992,
    'city_3' : 9993,
    'city_4' : 9994,
    'city_5' : 9995,
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)

print(population)
print(area)

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
dtype: int64


In [43]:
states=pd.DataFrame({
    'population1' : population,
    'area1' : area
})
print (states)

        population1  area1
city_1         1001   9991
city_2         1002   9992
city_3         1003   9993
city_4         1004   9994
city_5         1005   9995


In [45]:
print(states.values)
print(states.index)
print(states.columns)

print(type(states.values))
print(type(states.index))
print(type(states.columns))

[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['population1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


In [47]:
print (states['area1'])

city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [49]:
## DataFrame. Способы создания
#- через объекты Series
# - списки словарей
# - словари объектов Series
# - двумерный массив NumPy
# - структурированный массив NumPy

In [ ]:
# 2. Привести различные способы создания DataFrame.

In [ ]:
# Index - способ организации ссылки на данные объуктов Series и DataFrame, 
# неизменяем, упорядочен, являетмя мультимножеством(могут быть повторяющ. значения)


In [53]:
ind = pd.Index([2,3,5,7,11])
print(ind[1])
print(ind[::2])

3
Index([2, 5, 11], dtype='int64')


In [55]:
ind[1] = 5


TypeError: Index does not support mutable operations

In [57]:
#Index - следует соглашениям обьекта set (python)

In [61]:
indA = pd.Index([1,2,3,4,5])
indB = pd.Index([2,3,4,5,6])

print(indA.intersection(indB))

Index([2, 3, 4, 5], dtype='int64')


In [63]:
# Выборка данных из Series

In [65]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c', 'd'])

print ('a' in data)
print ('z' in data)


True
False


In [67]:
print (data.keys())

Index(['a', 'b', 'c', 'd'], dtype='object')


In [69]:
print (list(data.items()))

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]


In [71]:
data['a']=100
data['z']=1000

print(data)

a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64


In [73]:
## как одномерный массив

In [75]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c', 'd'])
print(data['a':'c'])
print(data[0:2])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64


In [77]:
print(data[data > 0.5])

c    0.75
d    1.00
dtype: float64


In [79]:
print(data[(data > 0.5) & (data <1 )])

c    0.75
dtype: float64


In [81]:
print(data[['a','d']])

a    0.25
d    1.00
dtype: float64


In [ ]:
# aтрибуты-индексаторы

In [90]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1,3,10,15])
print(data[1])

0.25


In [92]:
print (data.loc[1])
print (data.iloc[1])

0.25
0.5


In [94]:
# Выборка данных из DataFrame

In [100]:

pop = pd.Series (
    {
            'city_1' : 1001,
            'city_2' : 1002,
            'city_3' : 1003,
            'city_4' : 1004,
            'city_5' : 1005,
    }
)

area = pd.Series(
    {
            'city_1' : 9991,
            'city_2' : 9992,
            'city_3' : 9993,
            'city_4' : 9994,
            'city_5' : 9995,
    }
)
data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop' : pop})

print(data)
print(data['area1'])
print(data.area1)

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [98]:
print (data.pop1 is data['pop1'])

True


In [102]:
print (data.pop is data['pop'])

False


In [104]:
data['new'] = data['area1']

In [106]:
print(data)

        area1  pop1   pop   new
city_1   9991  1001  1001  9991
city_2   9992  1002  1002  9992
city_3   9993  1003  1003  9993
city_4   9994  1004  1004  9994
city_5   9995  1005  1005  9995


In [108]:
data['new1'] = data['area1'] / data['pop1']
print(data)

        area1  pop1   pop   new      new1
city_1   9991  1001  1001  9991  9.981019
city_2   9992  1002  1002  9992  9.972056
city_3   9993  1003  1003  9993  9.963111
city_4   9994  1004  1004  9994  9.954183
city_5   9995  1005  1005  9995  9.945274


In [110]:
# двумерный NumPy - массив

In [112]:
pop = pd.Series (
    {
            'city_1' : 1001,
            'city_2' : 1002,
            'city_3' : 1003,
            'city_4' : 1004,
            'city_5' : 1005,
    }
)

area = pd.Series(
    {
            'city_1' : 9991,
            'city_2' : 9992,
            'city_3' : 9993,
            'city_4' : 9994,
            'city_5' : 9995,
    }
)
data = pd.DataFrame({'area1':area, 'pop1':pop})
print(data)

        area1  pop1
city_1   9991  1001
city_2   9992  1002
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005


In [114]:
print(data.values)

[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]


In [116]:
print(data.T)

       city_1  city_2  city_3  city_4  city_5
area1    9991    9992    9993    9994    9995
pop1     1001    1002    1003    1004    1005


In [118]:
print(data['area1'])

city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [120]:
print(data.values[0])

[9991 1001]


In [122]:
print(data.values[0:3])

[[9991 1001]
 [9992 1002]
 [9993 1003]]


In [124]:
# атрибуты-индексаторы

In [126]:
data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop':pop})

In [128]:
print(data)
print(data.iloc[:3, 1:2])
print(data.loc[:'city_4','pop1':'pop'])

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
        pop1
city_1  1001
city_2  1002
city_3  1003
        pop1   pop
city_1  1001  1001
city_2  1002  1002
city_3  1003  1003
city_4  1004  1004


In [130]:
print(data.loc[data['pop'] > 1002, ['area1','pop']])

        area1   pop
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005


In [132]:
data.iloc[0,2] = 99999
print(data)

        area1  pop1    pop
city_1   9991  1001  99999
city_2   9992  1002   1002
city_3   9993  1003   1003
city_4   9994  1004   1004
city_5   9995  1005   1005


In [134]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0,10,4))

print(s)

0    9
1    0
2    5
3    8
dtype: int64


In [136]:
print (np.exp(s))

0    8103.083928
1       1.000000
2     148.413159
3    2980.957987
dtype: float64


In [140]:
pop = pd.Series (
    {
            'city_1' : 1001,
            'city_2' : 1002,
            'city_3' : 1003,
            'city_41' : 1004,
            'city_51' : 1005,
    }
)

area = pd.Series(
    {
            'city_1' : 9991,
            'city_2' : 9992,
            'city_3' : 9993,
            'city_42' : 9994,
            'city_52' : 9995,
    }
)

data = pd.DataFrame({'area1':area, 'pop1':pop})

print(data)

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     NaN  1004.0
city_42  9994.0     NaN
city_51     NaN  1005.0
city_52  9995.0     NaN


In [142]:
# Nan - not a number

In [144]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы
# вместо NaN было установлено значение 1

In [148]:
dfA = pd.DataFrame(rng.integers(0,10,(2,2)), columns =['a','b'])
dfB = pd.DataFrame(rng.integers(0,10,(3,3)), columns =['a','b', 'c'])

print(dfA)
print(dfB)

   a  b
0  9  0
1  6  6
   a  b  c
0  1  7  8
1  6  3  6
2  9  7  3


In [150]:
print (dfA + dfB)

      a    b   c
0  10.0  7.0 NaN
1  12.0  9.0 NaN
2   NaN  NaN NaN


In [152]:
rng = np.random.default_rng(1)

A = rng.integers(0, 10, (3,4))
print(A)

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]


In [154]:
print (A[0])

[4 5 7 9]


In [156]:
print (A-A[0])

[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]


In [158]:
df = pd.DataFrame(A, columns=['a','b','c','d'])
print(df)

   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4


In [160]:
print(df.iloc[0])

a    4
b    5
c    7
d    9
Name: 0, dtype: int64


In [162]:
print(df - df.iloc[0])

   a  b  c  d
0  0  0  0  0
1 -4 -4  1  0
2 -2 -2  1 -5


In [164]:
print (df.iloc[0, ::2])

a    4
c    7
Name: 0, dtype: int64


In [166]:
print (df - df.iloc[0, ::2])

     a   b    c   d
0  0.0 NaN  0.0 NaN
1 -4.0 NaN  1.0 NaN
2 -2.0 NaN  1.0 NaN


In [168]:
# 4. Переписать пример с транслированием для DataFrame так, чтобы вычитание происходило 
# по столбцам, а не по строкам

In [170]:
# NA - значения: NaN, null, -9999

In [172]:
# Pandas. Два способа хранения отстутсвующих значений
# индикаторы NaN, None
# null


In [174]:
# None - щбъект (накладные расходы). Не работает с sum, min

In [176]:
vall = np.array([1,2,3])
print (vall.sum())

6


In [178]:
vall = np.array([1,None,2,3])
print (vall.sum())

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [186]:
vall = np.array([1,np.nan,2,3])
print(vall)
print (np.nansum(vall))
print (np.sum(vall))
print (vall.sum())

[ 1. nan  2.  3.]
6.0
nan
nan


In [188]:
x = pd.Series(range(10), dtype=int)
print(x)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32


In [190]:
x[0] = None
x[1] = np.nan

print(x)

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64


In [192]:
x1 = pd.Series(['a','b','c'])
print(x1)

x1[0] = None
x1[1] = np.nan

print(x1)

0    a
1    b
2    c
dtype: object
0    None
1     NaN
2       c
dtype: object


In [194]:
# 

In [196]:
x2 = pd.Series([1,2,3,np.nan, None, pd.NA])
print(x2)

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object


In [198]:
x3 = pd.Series([1,2,3,np.nan, None, pd.NA], dtype = 'Int32')
print(x3)

0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32


In [200]:
print(x3.isnull())

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool


In [202]:
print(x3[x3.isnull()])

3    <NA>
4    <NA>
5    <NA>
dtype: Int32


In [204]:
print(x3[x3.notnull()])

0    1
1    2
2    3
dtype: Int32


In [206]:
print(x3.dropna())

0    1
1    2
2    3
dtype: Int32


In [210]:
df = pd.DataFrame(
    [
        [1,2,3, np.nan, None, pd.NA],
        [1,2,3,4,5,6],
        [1,np.nan,3,4,np.nan,6]
    ]
)

print(df)


   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6


In [212]:
print(df.dropna())

   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6


In [214]:
print(df.dropna(axis=0))


   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6


In [216]:
print(df.dropna(axis=1))

   0  2
0  1  3
1  1  3
2  1  3


In [218]:
# how
# - all - все значения NA
# - any - хотя бы одно значение
# - thresh = x, остается если присутствует МИНИМУМ X НЕПУСТЫХ значений


In [220]:
df = pd.DataFrame(
    [
        [1,2,3, np.nan, None, pd.NA],
        [1,2,3,None,5,6],
        [1,np.nan,3,None,np.nan,6]
    ]
)

print(df.dropna(axis=1, how = 'all'))
print(df.dropna(axis=1, how = 'any'))

   0    1  2    4     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  5.0     6
2  1  NaN  3  NaN     6
   0  2
0  1  3
1  1  3
2  1  3


In [222]:
print(df.dropna(axis=1, thresh=2))

   0    1  2     5
0  1  2.0  3  <NA>
1  1  2.0  3     6
2  1  NaN  3     6


In [ ]:
#5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()